[Window] Support `LOGICAL_OR` and `LOGICAL_AND`
Recidiviz/go-zetasqlite pull request #42
Opened 2024-04-03 21:03 UTC by ohaibbq

2024-04-03 21:50 UTC, ageiduschek requested changes

2024-04-03 21:50 UTC, ageiduschek commented on internal/function_window.go
> +	return BoolValue(true), nil
Should this not be `BoolValue(false)`? Like if there are no trues we return False?


Might make sense to include a test case like this:
```
SELECT LOGICAL_OR(a) OVER (ORDER BY b), a, b
FROM (
  SELECT CAST(a AS BOOL) AS a, b FROM UNNEST([
    STRUCT(False AS a, 1 AS b), 
    STRUCT(False AS a, 2 AS b), 
    STRUCT(True AS a, 3 AS b), 
    STRUCT(False AS a, 4 AS b)
  ])
);
```
and also one that tests what happens when there are no rows:
```
SELECT LOGICAL_OR(a) OVER (ORDER BY a)
FROM (
  SELECT CAST(a AS BOOL) AS a FROM UNNEST([]) a
);
```

2024-04-03 21:56 UTC, recidinick approved these changes

2024-04-05 21:15 UTC, ageiduschek approved these changes

2024-04-07 06:35 UTC, merged